base: "https://dixi-ost.de/"
baseVariants:
  - base: "%env(PLATFORM_ROUTES_CMS)%"
    condition: 'applicationContext == "Production/Platformsh"'
  - base: "https://%env(DOMAIN_CMS)%"
    condition: 'applicationContext == "Development/DDEV"'
languages:
  - title: Deutsch
    enabled: true
    languageId: 0
    base: /
    locale: de_DE.UTF-8
    navigationTitle: Deutsch
    flag: de
    hreflang: ""
    websiteTitle: ""
rootPageId: 1
websiteTitle: ""
