#!/usr/bin/env bash

## Description: Run magento CLI inside the web container
## Usage: magento [flags] [args]
## Example: "ddev magento list" or "ddev magento maintenance:enable" or "ddev magento sampledata:reset"
## ProjectTypes: php
## ExecRaw: true

if [ ! -f ${PATH_SHOP}/bin/magento ]; then
  echo '${PATH_SHOP}/bin/magento does not exist in your project root directory.'
  echo 'Please verify that you installed the shop in your project directory.'
  exit 1
fi

php ${PATH_SHOP}/bin/magento "$@"
